version: "3"
services:
  app:
    container_name: ProductsAPI
    restart: always
    environment:
      - MODE=docker
      - MONGO_URI_DOCKER=mongodb://mongo:27017/test
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
